# ═══════════════════════════════════════════════════════════════════════════════
# NYOWORKS Release Pipeline
# Creates releases with semantic versioning
# ═══════════════════════════════════════════════════════════════════════════════

name: Release

on:
  push:
    branches: [main]

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Release Please
        uses: google-github-actions/release-please-action@v4
        id: release
        with:
          release-type: node
          package-name: "@project/root"

      - uses: pnpm/action-setup@v4
        if: ${{ steps.release.outputs.release_created }}
        with:
          version: 9

      - uses: actions/setup-node@v4
        if: ${{ steps.release.outputs.release_created }}
        with:
          node-version: 22
          cache: "pnpm"
          registry-url: "https://registry.npmjs.org"

      - name: Publish Packages
        if: ${{ steps.release.outputs.release_created }}
        run: |
          pnpm install --frozen-lockfile
          pnpm turbo build
          pnpm publish -r --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
